import { useRef } from 'react';
import Head from 'next/head';
import LayoutDashboardThree from '@components/dashboardthree/LayoutDashboardThree';
import useScrollSpy from 'react-use-scrollspy';

function SideLink({ className, children }) {
  return (
    <li
      className={`${className} pb-0.5 text-neutral-600 transition-all hover:text-neutral-900 dark:text-gray-300 dark:hover:text-white`}
    >
      {children}
    </li>
  );
}

export default function Index() {
  const sectionRefs = [
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
    useRef(null),
  ];

  const activeSection = useScrollSpy({
    sectionElementRefs: sectionRefs,
    offsetPx: -200,
  });

  return (
    <>
      <Head>
        <title>Dashboard Three Column</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <LayoutDashboardThree>
        <div className='flex gap-x-4'>
          <div className='w-full'>
            <div
              ref={sectionRefs[0]}
              id='One'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-slate-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Example Dashboard Layout Three Column</h1>
            </div>
            <div
              ref={sectionRefs[1]}
              id='Two'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-red-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Two</h1>
            </div>
            <div
              ref={sectionRefs[2]}
              id='Three'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-orange-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Three</h1>
            </div>
            <div
              ref={sectionRefs[3]}
              id='Four'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-yellow-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Four</h1>
            </div>
            <div
              ref={sectionRefs[4]}
              id='Five'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-lime-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Five</h1>
            </div>
            <div
              ref={sectionRefs[5]}
              id='Six'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-emerald-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Six</h1>
            </div>
            <div
              ref={sectionRefs[6]}
              id='Seven'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-indigo-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Seven</h1>
            </div>
            <div
              ref={sectionRefs[7]}
              id='Eight'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-violet-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Eight</h1>
            </div>
            <div
              ref={sectionRefs[8]}
              id='Nine'
              className='mb-4 flex h-screen scroll-mt-14 items-center justify-center bg-pink-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Nine</h1>
            </div>
            <div
              ref={sectionRefs[9]}
              id='Ten'
              className='flex h-screen scroll-mt-14 items-center justify-center bg-rose-500'
            >
              <h1 className='px-8 text-2xl font-medium text-white'>Ten</h1>
            </div>
          </div>

          <div className='hidden w-32 text-sm lg:block'>
            <div className='sticky top-14'>
              <h5 className='mb-3 text-sm font-semibold text-gray-900 dark:text-white'>On This Page</h5>
              <nav>
                <ul className='flex flex-col gap-y-1'>
                  <SideLink className={activeSection === 0 && 'font-medium !text-blue-500'}>
                    <a href='#One'>One</a>
                  </SideLink>
                  <SideLink className={activeSection === 1 && 'font-medium !text-blue-500'}>
                    <a href='#Two'>Two</a>
                  </SideLink>
                  <SideLink className={activeSection === 2 && 'font-medium !text-blue-500'}>
                    <a href='#Three'>Three</a>
                  </SideLink>
                  <SideLink className={activeSection === 3 && 'font-medium !text-blue-500'}>
                    <a href='#Four'>Four</a>
                  </SideLink>
                  <SideLink className={activeSection === 4 && 'font-medium !text-blue-500'}>
                    <a href='#Five'>Five</a>
                  </SideLink>
                  <SideLink className={activeSection === 5 && 'font-medium !text-blue-500'}>
                    <a href='#Six'>Six</a>
                  </SideLink>
                  <SideLink className={activeSection === 6 && 'font-medium !text-blue-500'}>
                    <a href='#Seven'>Seven</a>
                  </SideLink>
                  <SideLink className={activeSection === 7 && 'font-medium !text-blue-500'}>
                    <a href='#Eight'>Eight</a>
                  </SideLink>
                  <SideLink className={activeSection === 8 && 'font-medium !text-blue-500'}>
                    <a href='#Nine'>Nine</a>
                  </SideLink>
                  <SideLink className={activeSection === 9 && 'font-medium !text-blue-500'}>
                    <a href='#Ten'>Ten</a>
                  </SideLink>
                </ul>
              </nav>
            </div>
          </div>
        </div>
      </LayoutDashboardThree>
    </>
  );
}
