import Head from 'next/head';
import Layout from '@components/sticky/Layout';

export default function Index() {
  return (
    <>
      <Head>
        <title>Sticky Sidebar until Footer</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <div className='flex h-96 items-center justify-center bg-orange-500'>
          <h1 className='px-8 text-2xl font-medium text-white'>Example Dashboard Layout Sticky Sidebar until Footer</h1>
        </div>
        <div className='h-96 bg-purple-500'></div>
        {/* <div className="bg-pink-500 h-96">
        </div> */}
      </Layout>
    </>
  );
}
