import { useContext } from 'react';
import Head from 'next/head';
import { AuthContext } from '@utils/useAuth';

import Footer from '@components/Footer';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';

export default function Third() {
  const user = useContext(AuthContext);

  return (
    <div>
      <Head>
        <title>Third Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 sm:px-6 md:px-8'>
          <section className='body-font text-gray-600'>
            <div className='mx-auto py-24'>
              <div className='mb-20 flex w-full flex-col text-center'>
                <h1 className='title-font mb-2 text-3xl font-medium text-gray-900 dark:text-neutral-200 sm:text-4xl'>
                  Auth from Context :<p>ID : {user.userID}</p>
                  <p>Name : {user.userName}</p>
                  <p>Email : {user.userEmail}</p>
                </h1>
                <h1 className='title-font mb-2 text-3xl font-medium text-gray-900 dark:text-neutral-200 sm:text-4xl'>
                  Pricing
                </h1>
                <p className='mx-auto text-base leading-relaxed dark:text-neutral-200 lg:w-2/3'>
                  Banh mi cornhole echo park skateboard authentic crucifix neutra tilde lyft biodiesel artisan direct
                  trade mumblecore 3 wolf moon twee
                </p>
              </div>
              <div className='-m-4 flex flex-wrap text-center'>
                <div className='w-full p-4 sm:w-1/2 md:w-1/4'>
                  <div className='rounded-lg border-2 border-gray-200 px-4 py-6'>
                    <svg
                      fill='none'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      className='mb-3 inline-block h-12 w-12 text-gray-800 dark:text-neutral-200'
                      viewBox='0 0 24 24'
                    >
                      <path d='M8 17l4 4 4-4m-4-5v9'></path>
                      <path d='M20.88 18.09A5 5 0 0018 9h-1.26A8 8 0 103 16.29'></path>
                    </svg>
                    <h2 className='title-font text-3xl font-medium text-gray-900 dark:text-neutral-200'>2.7K</h2>
                    <p className='leading-relaxed'>Downloads</p>
                  </div>
                </div>
                <div className='w-full p-4 sm:w-1/2 md:w-1/4'>
                  <div className='rounded-lg border-2 border-gray-200 px-4 py-6'>
                    <svg
                      fill='none'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      className='mb-3 inline-block h-12 w-12 text-gray-800 dark:text-neutral-200'
                      viewBox='0 0 24 24'
                    >
                      <path d='M17 21v-2a4 4 0 00-4-4H5a4 4 0 00-4 4v2'></path>
                      <circle cx='9' cy='7' r='4'></circle>
                      <path d='M23 21v-2a4 4 0 00-3-3.87m-4-12a4 4 0 010 7.75'></path>
                    </svg>
                    <h2 className='title-font text-3xl font-medium text-gray-900 dark:text-neutral-200'>1.3K</h2>
                    <p className='leading-relaxed'>Users</p>
                  </div>
                </div>
                <div className='w-full p-4 sm:w-1/2 md:w-1/4'>
                  <div className='rounded-lg border-2 border-gray-200 px-4 py-6'>
                    <svg
                      fill='none'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      className='mb-3 inline-block h-12 w-12 text-gray-800 dark:text-neutral-200'
                      viewBox='0 0 24 24'
                    >
                      <path d='M3 18v-6a9 9 0 0118 0v6'></path>
                      <path d='M21 19a2 2 0 01-2 2h-1a2 2 0 01-2-2v-3a2 2 0 012-2h3zM3 19a2 2 0 002 2h1a2 2 0 002-2v-3a2 2 0 00-2-2H3z'></path>
                    </svg>
                    <h2 className='title-font text-3xl font-medium text-gray-900 dark:text-neutral-200'>74</h2>
                    <p className='leading-relaxed'>Files</p>
                  </div>
                </div>
                <div className='w-full p-4 sm:w-1/2 md:w-1/4'>
                  <div className='rounded-lg border-2 border-gray-200 px-4 py-6'>
                    <svg
                      fill='none'
                      stroke='currentColor'
                      strokeLinecap='round'
                      strokeLinejoin='round'
                      strokeWidth='2'
                      className='mb-3 inline-block h-12 w-12 text-gray-800 dark:text-neutral-200'
                      viewBox='0 0 24 24'
                    >
                      <path d='M12 22s8-4 8-10V5l-8-3-8 3v7c0 6 8 10 8 10z'></path>
                    </svg>
                    <h2 className='title-font text-3xl font-medium text-gray-900 dark:text-neutral-200'>46</h2>
                    <p className='leading-relaxed'>Places</p>
                  </div>
                </div>
              </div>
            </div>
          </section>
        </main>

        <Footer />
      </Layout>
    </div>
  );
}
