import Head from 'next/head';

import Breadcrumb from '@components/Breadcrumb';
import ExDashboardNav from '@components/exdashboard/ExDashboardNav';
import ExMobileMenu from '@components/exdashboard/ExMobileMenu';
import ExSidebarMenu from '@components/exdashboard/ExSidebarMenu';
import ThemeToggle from '@components/exdashboard/ThemeToggle';
import Layout from '@components/Layout';

export default function Index() {
  return (
    <>
      <Head>
        <title>Second - Dashboard</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Layout>
        <ThemeToggle />

        <ExDashboardNav />

        <ExMobileMenu />

        <div className='mx-auto mt-2 h-full max-w-screen-2xl border px-2 dark:border-neutral-700'>
          <div className='h-full py-2 lg:flex'>
            <ExSidebarMenu />

            <main className='w-full border px-2 dark:border-neutral-700 lg:ml-60'>
              <Breadcrumb />

              <div className='flex h-96 items-center justify-center bg-teal-500'>
                <h1 className='px-8 text-2xl font-medium text-white'>{`The "Second" Menu Accordion Should Be Opened`}</h1>
              </div>
              <div className='h-96 bg-blue-500'></div>
              <div className='h-96 bg-red-500'></div>
            </main>
          </div>
        </div>
      </Layout>
    </>
  );
}
