import Head from "next/head";
import Layout from "@components/supabase/Layout";

export default function Index() {
  return (
    <>
      <Head>
        <title>First - Supabase Dashboard</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Layout>
        <div className="bg-orange-500 h-96 flex items-center justify-center">
          <h1 className="text-white font-medium text-2xl px-8">First Supabase Dashboard</h1>
        </div>
        <div className="bg-purple-500 h-96">
        </div>
        <div className="bg-pink-500 h-96">
        </div>
      </Layout>
    </>
  )
}