import { useContext } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BackToTop from '@components/BackToTop';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import { MoonIcon, SunIcon } from '@heroicons/react/outline';
import { GlobalContext } from '@utils/GlobalContext';

export default function Background() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <>
      <Head>
        <title>Background</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout className='relative bg-neutral-900'>
        <main className='mx-auto max-w-7xl px-4 py-8 sm:px-6 md:px-8'>
          <div className='relative my-16'>
            <Image
              className='absolute top-1/2 z-0'
              src='/ilustration/particle-left.svg'
              width={150}
              height={150}
              alt='illustration'
            />
            <Image
              className='absolute right-0 top-1/2 z-0'
              src='/ilustration/particle-right.svg'
              width={150}
              height={150}
              alt='illustration'
            />
            <div className='absolute left-0 z-0 h-[300px] w-[300px] translate-y-[50px] animate-pop rounded-full bg-orange-500 opacity-20 blur-[90px]'></div>
            <div className='absolute top-0 z-0 animate-pop rounded-full bg-emerald-500 opacity-20 blur-[90px] lg:h-[500px] lg:w-[500px] lg:translate-x-80'></div>
            <div className='absolute right-0 z-0 h-[350px] w-[350px] -translate-x-[100px] rounded-full bg-red-600 opacity-20 blur-[90px] lg:animate-blob'></div>
            <div className='relative z-[1] flex w-full justify-center'>
              <Image src='/ilustration/maintenance.svg' width={400} height={400} alt='illustration' />
            </div>
          </div>

          <div className='grid grid-cols-1 py-16 md:grid-cols-2'>
            <div className='relative'>
              <Image
                className='absolute top-1/2 z-0'
                src='/ilustration/particle-left.svg'
                width={150}
                height={150}
                alt='illustration'
              />
              <div className='absolute z-0 h-[300px] w-[300px] translate-y-[150px] animate-pop rounded-full bg-orange-600 opacity-20 blur-[90px]'></div>
              <div className='absolute right-0 z-0 h-[350px] w-[350px] -translate-x-[100px] rounded-full bg-emerald-600 opacity-20 blur-[120px] lg:animate-blob'></div>
              <div className='relative z-10 flex w-full justify-center'>
                <Image src='/ilustration/how-we-work.svg' width={400} height={400} alt='illustration' />
              </div>
            </div>
            <div className='relative z-10 flex flex-col justify-center text-white'>
              <div className='absolute right-0 top-0 z-0 h-[400px] w-[400px] animate-pop rounded-full bg-sky-500 opacity-20 blur-[120px]'></div>
              <p className='mb-8 text-3xl font-bold'>
                Everything is well planned, well designed and developed wholeheartedly Nostrud nostrud nostrud aliqua
                irure minim irure
              </p>
              <p className='text-lg text-neutral-200'>
                Careful planning makes us confident, developed with best practices so that the project can be
                maintained. We always test projects before they are shipped. Incididunt minim proident laborum dolor
                consequat. Labore excepteur ullamco duis labore incididunt cupidatat.{' '}
              </p>
            </div>
          </div>

          <div className='grid grid-cols-1 py-16 md:grid-cols-2'>
            <div className='relative z-10 flex flex-col justify-center text-white'>
              <div className='absolute top-0 z-0 h-[200px] w-[200px] animate-pop rounded-full bg-yellow-600 opacity-20 blur-[120px] lg:h-[400px] lg:w-[400px]'></div>
              <p className='mb-8 text-3xl font-bold'>
                Everything is well planned, well designed and developed wholeheartedly Nostrud nostrud nostrud aliqua
                irure minim irure
              </p>
              <p className='text-lg text-neutral-200'>
                Careful planning makes us confident, developed with best practices so that the project can be
                maintained. We always test projects before they are shipped. Incididunt minim proident laborum dolor
                consequat. Labore excepteur ullamco duis labore incididunt cupidatat.{' '}
              </p>
            </div>
            <div className='relative'>
              <Image
                className='absolute right-0 top-1/2 z-0'
                src='/ilustration/particle-right.svg'
                width={150}
                height={150}
                alt='illustration'
              />
              <div className='absolute z-0 h-[300px] w-[300px] animate-pop rounded-full bg-pink-500 opacity-20 blur-[90px] lg:translate-x-[250px] lg:translate-y-[150px]'></div>
              <div className='absolute z-0 h-[150px] w-[150px] rounded-full bg-purple-700 opacity-20 blur-[120px] lg:h-[350px] lg:w-[350px] lg:animate-blob'></div>
              <div className='relative z-[1] flex w-full justify-center'>
                <Image src='/ilustration/development.svg' width={400} height={400} alt='illustration' />
              </div>
            </div>
          </div>

          <section className='my-20 border border-neutral-800 text-white dark:border-neutral-800'>
            <div className='p-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div
              className='mx-8 h-64 bg-cover bg-fixed bg-center'
              style={{ backgroundImage: 'url(/background/parallax.avif)' }}
            ></div>
            <div className='p-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
          </section>

          <section className='my-20 border border-neutral-800 text-white dark:border-neutral-800'>
            <div className='p-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div
              className='mx-8 h-64 bg-cover bg-fixed bg-center'
              style={{ backgroundImage: 'url(/background/parallax.avif)' }}
            >
              <div className='flex h-full w-full items-center justify-center bg-black/60'>
                <div className='text-center'>
                  <h3 className='mb-2 text-3xl font-bold'>Title</h3>
                  <h5 className='mb-8 text-xl font-semibold'>Sub Title</h5>
                  <Link
                    href='/background#'
                    className='rounded bg-white px-4 py-1.5 text-base font-medium text-neutral-600 shadow-lg transition-all duration-300 hover:bg-neutral-200'
                  >
                    BACKGROUND
                  </Link>
                </div>
              </div>
            </div>
            <div className='p-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
            <div className='px-8 pb-8'>
              <p>
                Duis sunt consequat ullamco est ex reprehenderit magna laborum consectetur sunt aliquip eu esse nisi.
                Dolore adipisicing elit amet cillum ad labore elit labore. Fugiat consectetur cupidatat anim sint veniam
                aute fugiat dolore eiusmod fugiat eiusmod magna incididunt enim. Minim dolore reprehenderit in sit
                cupidatat commodo consequat. Quis veniam officia incididunt sunt deserunt cillum occaecat do ipsum quis
                aliquip. Aute non fugiat amet dolor dolor quis in minim.
              </p>
            </div>
          </section>

          <div className='fixed bottom-20 right-3 z-10 mx-4 rounded bg-gray-100 bg-opacity-20 !py-2 px-2 backdrop-blur backdrop-filter dark:bg-neutral-800 dark:bg-opacity-40 md:right-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-neutral-800 p-1 text-white transition-all duration-300 ease-in hover:bg-neutral-700'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-gray-100 p-1 transition-all duration-300 ease-in hover:bg-gray-200'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>
      </Layout>
    </>
  );
}
