import { useContext } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BackToTop from '@components/BackToTop';
import Footer from '@components/Footer';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import Section from '@components/Section';
import TocLink from '@components/TocLink';
import { ArrowRightIcon, MoonIcon, PhotographIcon, PlayIcon, SunIcon } from '@heroicons/react/outline';
import { GlobalContext } from '@utils/GlobalContext';
import { twMerge } from 'tailwind-merge';

export default function Card() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  return (
    <div>
      <Head>
        <title>Card Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 pb-16 sm:px-6 md:px-8'>
          <Section id='components' name='Card TOC'>
            <div className='grid sm:grid-cols-2 md:grid-cols-3'>
              <div>
                <TocLink href='#card-design' text='Card Design' />
              </div>
              <div>
                <TocLink href='#card-item' text='Card Item' />
              </div>
              <div>
                <TocLink href='#card-list' text='Card List' />
              </div>
            </div>
          </Section>

          <Section id='card-design' name='Card Design'>
            <div className='grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4'>
              <div className='group relative rounded-md bg-gray-100 shadow dark:bg-neutral-800'>
                <div className='relative h-64 w-full transition-all duration-300 group-hover:opacity-90'>
                  <Image
                    className='h-full w-full rounded-t-md object-cover object-center lg:h-full lg:w-full'
                    src='https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80'
                    alt='hero'
                    layout='fill'
                  />
                </div>
                <div className='m-4 flex justify-between'>
                  <div>
                    <h3 className='text-base font-medium text-gray-700 transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                      <a href='#'>
                        <span aria-hidden='true' className='absolute inset-0'></span>
                        Nature
                      </a>
                    </h3>
                  </div>
                  <p className='text-sm font-medium text-gray-900 dark:text-white'>$35</p>
                </div>
              </div>

              <div className='group relative rounded-md bg-gray-100 dark:bg-neutral-800'>
                <div className='rounded-md pb-2 shadow transition-all duration-300 group-hover:shadow-lg'>
                  <div className='relative h-64 w-full transition-all duration-300 group-hover:opacity-90'>
                    <Image
                      className='h-full w-full rounded-t-md object-cover object-center lg:h-full lg:w-full'
                      src='https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80'
                      alt='hero'
                      layout='fill'
                    />
                  </div>
                  <div className='m-4 flex justify-between'>
                    <div>
                      <h3 className='text-base font-medium text-gray-700 transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                        <a href='#'>
                          <span aria-hidden='true' className='absolute inset-0'></span>
                          Nature
                        </a>
                      </h3>
                    </div>
                    <p className='text-sm font-medium text-gray-900 dark:text-white'>$35</p>
                  </div>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='relative flex h-64 min-h-full w-full flex-wrap items-center rounded-md bg-black'>
                  <Image
                    className='absolute inset-0 block h-full w-full rounded-md object-cover object-center opacity-40'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='relative z-10 w-full text-center'>
                    <h3 className='text-2xl font-medium text-white transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                      <a href='#'>Nature</a>
                    </h3>
                    <p className='text-gray-100'>mustache fixie paleo lumbersexual.</p>
                  </div>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='relative flex h-64 min-h-full w-full flex-wrap items-end'>
                  <Image
                    className='absolute inset-0 h-full w-full rounded-md object-cover object-center'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='z-10 w-full rounded-b-md bg-black bg-opacity-40 p-3'>
                    <h3 className='text-2xl font-medium text-white transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                      <a href='#'>Nature</a>
                    </h3>
                    <p className='text-gray-100'>mustache fixie paleo lumbersexual.</p>
                  </div>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='relative flex h-64 min-h-full w-full flex-wrap'>
                  <Image
                    className='absolute inset-0 h-full w-full rounded-md object-cover object-center'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='z-10 h-full w-full rounded-md bg-black bg-opacity-50 p-3'>
                    <h3 className='text-2xl font-medium text-white transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                      <a href='#'>Nature</a>
                    </h3>
                    <p className='text-gray-100'>mustache fixie paleo lumbersexual.</p>
                  </div>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='relative flex h-64 min-h-full w-full flex-wrap'>
                  <Image
                    className='absolute inset-0 h-full w-full rounded-md object-cover object-center'
                    src='https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='z-10 flex h-full w-full items-center rounded-md bg-black bg-opacity-50 p-3'>
                    <div>
                      <h3 className='text-2xl font-medium text-white transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                        <a href='#'>Nature</a>
                      </h3>
                      <p className='text-gray-100'>mustache fixie paleo lumbersexual.</p>
                    </div>
                  </div>
                </div>
              </div>

              <div className='group cursor-pointer'>
                <div className='relative flex h-64 min-h-full w-full flex-wrap'>
                  <Image
                    className='absolute inset-0 h-full w-full rounded-md object-cover object-center'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='z-10 flex h-full w-full items-end rounded-md bg-black bg-opacity-50 p-3'>
                    <div>
                      <h3 className='text-2xl font-medium text-white transition-all duration-300 group-hover:text-blue-500 dark:text-white'>
                        <a href='#'>Nature</a>
                      </h3>
                      <p className='text-gray-100'>mustache fixie paleo lumbersexual.</p>
                    </div>
                  </div>
                </div>
              </div>

              <a
                href=''
                className='group relative block overflow-hidden rounded-xl bg-cover bg-center bg-no-repeat'
                style={{
                  backgroundImage:
                    'url(' + 'https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80' + ')',
                }}
              >
                <span className='absolute right-4 top-4 z-10 inline-flex items-center rounded-full bg-black px-3 py-1 text-xs font-semibold text-white'>
                  4.5
                  <svg
                    xmlns='http://www.w3.org/2000/svg'
                    className='ml-1.5 h-4 w-4 text-yellow-300'
                    viewBox='0 0 20 20'
                    fill='currentColor'
                  >
                    <path d='M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.07 3.292a1 1 0 00.95.69h3.462c.969 0 1.371 1.24.588 1.81l-2.8 2.034a1 1 0 00-.364 1.118l1.07 3.292c.3.921-.755 1.688-1.54 1.118l-2.8-2.034a1 1 0 00-1.175 0l-2.8 2.034c-.784.57-1.838-.197-1.539-1.118l1.07-3.292a1 1 0 00-.364-1.118L2.98 8.72c-.783-.57-.38-1.81.588-1.81h3.461a1 1 0 00.951-.69l1.07-3.292z' />
                  </svg>
                </span>
                <div className='relative h-full bg-black bg-opacity-40 px-4 pt-44 text-white'>
                  <h5 className='text-2xl font-bold transition-all duration-300 group-hover:text-blue-500'>Nature</h5>
                  <p className='text-sm'>Nature</p>
                </div>
              </a>

              <div className='group'>
                <div
                  className='h-64 w-full rounded-lg bg-gray-300 bg-cover bg-center shadow-md'
                  style={{
                    backgroundImage:
                      'url(' + 'https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80' + ')',
                  }}
                ></div>
                <div className='mx-auto -mt-10 w-56 overflow-hidden rounded-lg bg-white shadow-lg dark:bg-gray-800'>
                  <h3 className='py-2 text-center font-bold uppercase tracking-wide text-gray-800 dark:text-white'>
                    Nature
                  </h3>
                  <div className='flex items-center justify-between bg-gray-100 px-3 py-2 dark:bg-gray-700'>
                    <span className='font-bold text-gray-800 dark:text-gray-200'>$129</span>
                    <button className='transform rounded bg-gray-800 px-2 py-1 text-xs font-semibold uppercase text-white transition-colors duration-200 hover:bg-gray-700 focus:bg-gray-700 focus:outline-none dark:hover:bg-gray-600 dark:focus:bg-gray-600'>
                      Add to cart
                    </button>
                  </div>
                </div>
              </div>

              <div
                className='relative flex h-64 w-full items-end justify-start bg-gray-500 bg-cover bg-center text-left'
                style={{
                  backgroundImage:
                    'url(' + 'https://images.unsplash.com/photo-1629447236132-22c57cd0f0bf?w=640&q=80' + ')',
                }}
              >
                <div className='absolute bottom-0 left-0 right-0 top-0 bg-gradient-to-b from-gray-900 via-transparent to-gray-900'></div>
                <div className='absolute left-0 right-0 top-0 mx-5 mt-3 flex items-center justify-between'>
                  <a
                    rel='noopener noreferrer'
                    href='#'
                    className='bgundefined px-3 py-2 text-xs font-semibold uppercase tracking-wider text-gray-100'
                  >
                    Politics
                  </a>
                  <div className='flex flex-col justify-start text-center text-gray-100'>
                    <span className='text-3xl font-semibold leading-none tracking-wide'>04</span>
                    <span className='uppercase leading-none'>Aug</span>
                  </div>
                </div>
                <h2 className='z-10 p-5'>
                  <a rel='noopener noreferrer' href='#' className='text-md font-medium text-gray-100 hover:underline'>
                    Nature
                  </a>
                </h2>
              </div>

              <div className='relative h-64 overflow-hidden rounded-lg bg-cover bg-no-repeat shadow-lg'>
                <Image
                  className='w-full'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                  alt='hero'
                  layout='fill'
                />
                <a href='#!'>
                  <div className='absolute bottom-0 left-0 right-0 top-0 h-full w-full overflow-hidden bg-black bg-opacity-40 bg-fixed'>
                    <div className='flex h-full items-end justify-start'>
                      <div className='m-6 text-white'>
                        <h5 className='text-lg font-bold'>Nature</h5>
                        <p>
                          <small>nature</small>
                        </p>
                      </div>
                    </div>
                  </div>
                </a>
              </div>

              <div className='relative h-64 overflow-hidden rounded-lg'>
                <Image
                  className='w-full'
                  alt='hero'
                  layout='fill'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                />
                <div className='absolute bottom-5 w-full text-center'>
                  <div className='mx-5 overflow-hidden rounded-lg bg-white p-3'>
                    <h3 className='text-dark text-base font-semibold'>Nature</h3>
                    <p className='text-sm'>Nature</p>
                  </div>
                </div>
              </div>

              <a href='#!' className='group relative h-64 overflow-hidden rounded-md'>
                <Image
                  className='w-full transform rounded-md object-center transition-transform duration-500 group-hover:scale-125'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                  alt='hero'
                  layout='fill'
                />
                <div className='absolute inset-0 rounded-md bg-black bg-opacity-40'>
                  <div className='flex h-full items-end justify-center'>
                    <div className='m-6 text-white'>
                      <h5 className='line-clamp-2 text-center text-lg font-semibold'>
                        Hover Image Zoom Elit ex minim fugiat tempor ut id exercitation fugiat tempor ut id exercitation
                      </h5>
                    </div>
                  </div>
                </div>
              </a>

              <a
                href='#!'
                className='group relative h-64 transform overflow-hidden rounded-md transition-transform duration-300 ease-in-out hover:-translate-y-2'
              >
                <Image
                  className='w-full rounded-md object-center'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                  alt='hero'
                  layout='fill'
                />
                <div className='absolute inset-0 rounded-md bg-black bg-opacity-40'>
                  <div className='flex h-full items-end justify-center'>
                    <div className='m-6 text-white'>
                      <h5 className='line-clamp-2 text-center text-lg font-semibold'>Hover Image Translate</h5>
                    </div>
                  </div>
                </div>
              </a>

              <a
                href='#!'
                className='group relative h-64 transform overflow-hidden rounded-md transition-transform duration-300 ease-in-out hover:-translate-y-2'
              >
                <Image
                  className='w-full rounded-md object-center'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                  alt='hero'
                  layout='fill'
                />
                <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
                  <div className='flex h-full items-end justify-center'>
                    <div className='m-6 text-white'>
                      <h5 className='line-clamp-2 text-center text-lg font-semibold'>Image Gradient </h5>
                    </div>
                  </div>
                </div>
              </a>

              <a href='#!' className='group relative h-64 overflow-hidden rounded-md'>
                <Image
                  className='w-full rounded-md object-center brightness-90 transition-all duration-300 group-hover:brightness-100'
                  src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                  alt='hero'
                  layout='fill'
                />
                <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
                  <div className='flex h-full items-end justify-center'>
                    <div className='m-6 text-white'>
                      <h5 className='line-clamp-2 text-center text-lg font-semibold'>Hover Image Brightness</h5>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </Section>

          <Section id='card-item' name='Card Item'>
            <div className='grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4'>
              <div className='group relative h-64 overflow-hidden rounded-md'>
                <Image
                  className='w-full rounded-md object-cover brightness-90 transition-all duration-300 group-hover:brightness-100'
                  src='https://img.youtube.com/vi/GfO-3Oir-qM/hqdefault.jpg'
                  alt='hero'
                  layout='fill'
                  unoptimized
                />
                <button
                  onClick={() => {
                    alert('clicked');
                  }}
                  className='group absolute inset-0 cursor-pointer rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950 focus-visible:outline-none'
                >
                  <div className='flex h-full items-center justify-center'>
                    <div className='rounded-md bg-neutral-800/80 p-3 text-white transition-all duration-300 group-hover:bg-red-600 group-focus-visible:outline-none group-focus-visible:ring-2 group-focus-visible:ring-sky-500'>
                      <PlayIcon className='h-5 w-5' />
                    </div>
                  </div>
                  <div className='absolute inset-x-0 bottom-0'>
                    <p className='line-clamp-2 px-4 pb-4 text-center text-base font-medium text-white'>
                      Video Player onClick
                    </p>
                  </div>
                </button>
              </div>

              <div className='relative'>
                <div className='group relative h-64 overflow-hidden rounded-md'>
                  <Image
                    className='w-full rounded-md object-cover brightness-90 transition-all duration-300 group-hover:brightness-100'
                    src='https://img.youtube.com/vi/GfO-3Oir-qM/hqdefault.jpg'
                    alt='hero'
                    layout='fill'
                    unoptimized
                  />
                  <button
                    onClick={() => {
                      alert('clicked');
                    }}
                    className='group absolute inset-0 cursor-pointer rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950 focus-visible:outline-none'
                  >
                    <div className='flex h-full items-center justify-center'>
                      <div className='rounded-md bg-neutral-800/80 p-3 text-white transition-all duration-300 group-hover:bg-red-600 group-focus-visible:outline-none group-focus-visible:ring-2 group-focus-visible:ring-sky-500'>
                        <PlayIcon className='h-5 w-5' />
                      </div>
                    </div>
                    <div className='absolute inset-x-0 bottom-0'>
                      <p className='line-clamp-2 px-4 pb-4 text-center text-base font-medium text-white'>
                        Video Player onClick
                      </p>
                    </div>
                  </button>
                </div>
                <button
                  title={`Delete`}
                  className={twMerge(
                    'absolute -right-1.5 -top-1.5 rounded-full px-2 py-1 text-xs font-medium',
                    'bg-red-500 text-white transition-all hover:bg-red-600',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 focus-visible:ring-offset-1',
                  )}
                >
                  X
                </button>
              </div>

              <div className='relative'>
                <div className='grid'>
                  <Link
                    href='#'
                    className='group overflow-hidden rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500'
                  >
                    <div className='relative h-64 overflow-hidden'>
                      <Image
                        className='w-full transform object-cover brightness-90 transition-all duration-500 group-hover:scale-110 group-hover:brightness-100'
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        alt='hero'
                        layout='fill'
                        unoptimized
                      />
                    </div>
                    <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
                      <div className='flex h-full items-end justify-center'>
                        <p className='line-clamp-2 px-4 pb-4 text-center text-base font-medium text-white'>Title</p>
                      </div>
                    </div>
                  </Link>
                </div>
              </div>

              <div className='relative'>
                <div className='grid'>
                  <Link
                    href='#'
                    className='group overflow-hidden rounded-md focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500'
                  >
                    <div className='relative h-64 overflow-hidden'>
                      <Image
                        className='w-full transform object-cover brightness-90 transition-all duration-500 group-hover:scale-110 group-hover:brightness-100'
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        alt='hero'
                        layout='fill'
                        unoptimized
                      />
                    </div>
                    <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
                      <div className='flex h-full items-end justify-center'>
                        <p className='line-clamp-2 px-4 pb-4 text-center text-base font-medium text-white'>Title</p>
                      </div>
                    </div>
                  </Link>
                </div>
                <button
                  title={`Delete`}
                  className={twMerge(
                    'absolute -right-1.5 -top-1.5 rounded-full px-2 py-1 text-xs font-medium',
                    'bg-red-500 text-white transition-all hover:bg-red-600',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400 focus-visible:ring-offset-1',
                  )}
                >
                  X
                </button>
              </div>

              <Link
                href='#'
                className='group rounded p-2 text-center focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500'
              >
                <div className='relative mx-auto mb-2 h-44 w-44 overflow-hidden'>
                  <Image
                    alt={'lala'}
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    className={`transform rounded-full brightness-90 transition duration-500 ease-in-out will-change-auto group-hover:brightness-110`}
                    fill
                    unoptimized
                  />
                </div>
                <p className='transition-all duration-500 group-hover:text-sky-500'>Band Name</p>
              </Link>

              <Link
                href='#'
                className='group rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500'
              >
                <div className='relative mb-2 h-52'>
                  <Image
                    alt={'lala'}
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    fill
                    unoptimized
                    className='rounded'
                  />
                </div>
                <p className='transition-all duration-500 group-hover:text-sky-500'>Genre Name</p>
              </Link>

              <div
                className={`flex h-20 items-center justify-between gap-2 rounded border p-2 dark:border-neutral-800`}
              >
                <Link
                  href='#'
                  className='group rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500'
                >
                  <div className='flex items-center gap-2'>
                    <div className='relative h-12 w-12 overflow-hidden rounded'>
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        className='transform rounded-t brightness-90 transition duration-500 ease-in-out will-change-auto group-hover:brightness-110'
                        fill
                        unoptimized
                      />
                    </div>
                    <div>
                      <p className='mb-1 transition-all duration-500 group-hover:text-sky-500'>Song Name</p>
                      <p className='text-[13px]'>Band Name</p>
                    </div>
                  </div>
                </Link>
                <button
                  title='Play Preview'
                  className='rounded text-neutral-600 transition-all duration-300 hover:text-sky-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:text-neutral-200 dark:hover:text-sky-500'
                >
                  <PlayIcon className='h-7 w-7 ' />
                </button>
              </div>

              <Link
                href='#'
                className={`group rounded border p-0 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:border-neutral-800`}
              >
                <div className='relative h-52 overflow-hidden sm:h-44'>
                  <Image
                    alt={'lala'}
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    className={`group-hover:brightness-11 transform rounded-t brightness-90 transition duration-500 ease-in-out will-change-auto`}
                    fill
                    unoptimized
                  />
                </div>
                <div className='p-4'>
                  <p className='mb-1 transition-all duration-500 group-hover:text-sky-500'>Album Name</p>
                  <p className='text-[13px]'>Artist Name</p>
                </div>
              </Link>

              <Link
                href='#'
                className={twMerge(
                  'group mx-auto w-40 rounded border shadow dark:border-neutral-800 sm:w-[12rem]',
                  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500',
                )}
              >
                <div className='relative h-56 w-full overflow-hidden sm:h-64'>
                  {true ? (
                    <Image
                      alt={'lala'}
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      className={`transform rounded-t brightness-90 transition duration-500 ease-in-out will-change-auto group-hover:brightness-110`}
                      fill
                    />
                  ) : (
                    <div className='flex h-full w-full items-center justify-center rounded-t bg-neutral-200 dark:bg-neutral-800'>
                      <PhotographIcon className='h-16 w-16 text-neutral-500' />
                    </div>
                  )}
                </div>
                <div className='p-3.5'>
                  <p className='mb-1 line-clamp-2 !text-[15px] transition-all duration-500 group-hover:text-sky-500'>
                    Movie Title
                  </p>
                  <span className='text-[13px] text-neutral-600 dark:text-neutral-400'>movie date</span>
                </div>
              </Link>

              <Link href='#' className='group rounded focus-visible:outline-none'>
                <div className='m-1 h-[320px] rounded border shadow dark:border-neutral-800 sm:h-[354px]'>
                  <div className='relative h-56 w-full overflow-hidden sm:h-64'>
                    {true ? (
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        className={twMerge(
                          'rounded-t brightness-90 group-hover:brightness-110',
                          'transform transition duration-500 ease-in-out will-change-auto',
                        )}
                        fill
                      />
                    ) : (
                      <div className='flex h-full w-full items-center justify-center rounded-t bg-neutral-200 dark:bg-neutral-800'>
                        <PhotographIcon className='h-16 w-16 text-neutral-500' />
                      </div>
                    )}
                  </div>
                  <div className='px-2.5 py-3'>
                    <p
                      className={twMerge(
                        'line-clamp-2 rounded px-1 py-0.5 !text-[15px] transition-all duration-500',
                        'group-hover:text-sky-500 group-focus-visible:ring-2 group-focus-visible:ring-sky-500',
                      )}
                    >
                      Movie Title
                    </p>
                    <span className='px-1 text-[13px] text-neutral-600 dark:text-neutral-400'>movie date</span>
                  </div>
                </div>
              </Link>

              <Link href='#' className='group rounded focus-visible:outline-none'>
                <div className='m-1 h-[280px] rounded border shadow dark:border-neutral-800 sm:h-[295px]'>
                  <div className='relative h-52 w-full overflow-hidden sm:h-56'>
                    {true ? (
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        className={twMerge(
                          'rounded-t brightness-90 group-hover:brightness-110',
                          'transform transition duration-500 ease-in-out will-change-auto',
                        )}
                        fill
                      />
                    ) : (
                      <div className='flex h-full w-full items-center justify-center rounded-t bg-neutral-200 dark:bg-neutral-800'>
                        <PhotographIcon className='h-16 w-16 text-neutral-500' />
                      </div>
                    )}
                  </div>
                  <div className='px-2.5 py-3'>
                    <p
                      className={twMerge(
                        'line-clamp-2 rounded px-1 py-0.5 !text-[15px] transition-all duration-500',
                        'group-hover:text-sky-500 group-focus-visible:ring-2 group-focus-visible:ring-sky-500',
                      )}
                    >
                      Actor Name
                    </p>
                  </div>
                </div>
              </Link>

              <Link href='#' className='group rounded focus-visible:outline-none'>
                <div className='relative mx-auto h-32 w-32 max-w-[8rem] overflow-hidden'>
                  {true ? (
                    <Image
                      alt='lala'
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      className={twMerge(
                        'rounded-full object-cover brightness-90 group-hover:brightness-110',
                        'transform transition duration-500 ease-in-out will-change-auto',
                      )}
                      fill
                    />
                  ) : (
                    <div className='flex h-full w-full items-center justify-center rounded-full bg-neutral-200 dark:bg-neutral-800'>
                      <PhotographIcon className='h-16 w-16 text-neutral-500' />
                    </div>
                  )}
                </div>
                <div className='px-2.5 pt-3'>
                  <p
                    className={twMerge(
                      'line-clamp-2 rounded px-1 py-0.5 text-center !text-[15px] transition-all duration-500',
                      'group-hover:text-sky-500 group-focus-visible:ring-2 group-focus-visible:ring-sky-500',
                    )}
                  >
                    Director Name
                  </p>
                </div>
              </Link>

              <Link
                href='#'
                className={twMerge(
                  'group mx-auto rounded',
                  'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500',
                )}
              >
                <div className={`relative h-24 w-52 overflow-hidden contrast-125`}>
                  {true ? (
                    <Image
                      alt='lala'
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      className={`group-hover:brightness-110} transform object-contain brightness-90 transition duration-500 ease-in-out will-change-auto`}
                      fill
                    />
                  ) : (
                    <div className='flex h-full w-full items-center justify-center rounded-t bg-neutral-200 dark:bg-neutral-800'>
                      <PhotographIcon className='h-16 w-16 text-neutral-500' />
                    </div>
                  )}
                </div>
                <div className='p-3 pb-2'>
                  <p className='mb-1 line-clamp-2 text-center !text-[15px] transition-all duration-500 group-hover:text-sky-500'>
                    Studio Name
                  </p>
                </div>
              </Link>

              <Link href='#' className='group rounded focus-visible:outline-none'>
                <div className='h-[316px] rounded border shadow dark:border-neutral-800 sm:h-[354px]'>
                  <div className='relative h-56 w-full overflow-hidden sm:h-64'>
                    {true ? (
                      <Image
                        title='title'
                        alt='lala'
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        className={twMerge(
                          'rounded-t brightness-90 group-hover:brightness-110',
                          'transform transition duration-500 ease-in-out will-change-auto',
                        )}
                        fill
                        unoptimized
                      />
                    ) : (
                      <div className='flex h-full w-full items-center justify-center rounded-t bg-neutral-200 dark:bg-neutral-800'>
                        <PhotographIcon className='h-16 w-16 text-neutral-500' />
                      </div>
                    )}
                  </div>
                  <div className='px-2.5 py-3'>
                    <p
                      className={twMerge(
                        'line-clamp-2 rounded px-1 py-0.5 !text-[15px] transition-all duration-500',
                        'group-hover:text-sky-500 group-focus-visible:ring-2 group-focus-visible:ring-sky-500',
                      )}
                    >
                      Book Title
                    </p>
                    <span className='line-clamp-1 px-1 text-[14px] text-neutral-600 dark:text-neutral-400'>
                      Author Name
                    </span>
                  </div>
                </div>
              </Link>

              <Link href='#' className='group rounded focus-visible:outline-none'>
                <div className='relative mx-auto h-32 w-32 max-w-[8rem] overflow-hidden'>
                  {true ? (
                    <Image
                      alt='lala'
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      className={twMerge(
                        'rounded-full object-cover brightness-90 group-hover:brightness-110',
                        'transform transition duration-500 ease-in-out will-change-auto',
                      )}
                      fill
                      unoptimized
                    />
                  ) : (
                    <div className='flex h-full w-full items-center justify-center rounded-full bg-neutral-200 dark:bg-neutral-800'>
                      <PhotographIcon className='h-16 w-16 text-neutral-500' />
                    </div>
                  )}
                </div>
                <div className='px-2.5 pt-3'>
                  <p
                    className={twMerge(
                      'line-clamp-2 rounded px-1 py-0.5 text-center !text-[15px] transition-all duration-500',
                      'group-hover:text-sky-500 group-focus-visible:ring-2 group-focus-visible:ring-sky-500',
                    )}
                  >
                    Author Name
                  </p>
                  <span className='line-clamp-1 px-1 text-center text-[14px] text-neutral-500 dark:text-neutral-400'>
                    10 Published book
                  </span>
                </div>
              </Link>
            </div>
          </Section>

          <Section id='card-list' name='Card List'>
            <div className='mt-2 flex flex-col gap-8 pb-4'>
              <Link
                href='#'
                className='group flex gap-4 rounded border shadow focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:border-neutral-800'
              >
                <div className='w-[88px]'>
                  <div className='relative h-32 w-[88px] overflow-hidden'>
                    {true ? (
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        className={`transform rounded-l brightness-90 transition duration-500 ease-in-out will-change-auto group-hover:brightness-110`}
                        fill
                      />
                    ) : (
                      <div className='flex h-full w-full items-center justify-center rounded-l bg-neutral-200 dark:bg-neutral-800'>
                        <PhotographIcon className='h-16 w-16 text-neutral-500' />
                      </div>
                    )}
                  </div>
                </div>
                <div className='pr-3 pt-3.5'>
                  <p className='mb-1 line-clamp-2 !text-[15px] transition-all duration-500 group-hover:text-sky-500'>
                    Movie Name
                  </p>
                  <span className='text-[13px] text-neutral-600 dark:text-neutral-400'>movie date</span>
                  <p className='mt-2 line-clamp-2 font-normal'>Movie Description</p>
                </div>
              </Link>

              <div className='flex gap-3'>
                <Link
                  href='#'
                  className='rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500'
                >
                  {true ? (
                    <div className='relative h-20 w-14'>
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        fill
                        className={twMerge('rounded object-cover brightness-90 hover:brightness-100')}
                        unoptimized
                      />
                    </div>
                  ) : (
                    <div className='flex h-20 w-14 items-center justify-center rounded bg-neutral-200 dark:bg-neutral-800'>
                      <PhotographIcon className='h-8 w-8 text-neutral-500' />
                    </div>
                  )}
                </Link>
                <div>
                  <Link
                    href='#'
                    className={twMerge(
                      'rounded text-[15px] font-medium text-neutral-700 transition-all duration-200 dark:text-neutral-100',
                      'hover:text-sky-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500',
                    )}
                  >
                    Book Title
                  </Link>
                  <p className='mt-1 text-sm text-neutral-600 dark:text-neutral-200'>book date</p>
                </div>
              </div>

              <div className='relative'>
                <div className='flex gap-3'>
                  <Link
                    href='#'
                    className='rounded focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500'
                  >
                    {true ? (
                      <div className='relative h-20 w-14'>
                        <Image
                          alt={'lala'}
                          src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                          fill
                          className={twMerge('rounded object-cover brightness-90 hover:brightness-100')}
                          unoptimized
                        />
                      </div>
                    ) : (
                      <div className='flex h-20 w-14 items-center justify-center rounded bg-neutral-200 dark:bg-neutral-800'>
                        <PhotographIcon className='h-8 w-8 text-neutral-500' />
                      </div>
                    )}
                  </Link>
                  <div>
                    <Link
                      href='#'
                      className={twMerge(
                        'rounded text-[15px] font-medium text-neutral-700 transition-all duration-200 dark:text-neutral-100',
                        'hover:text-sky-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500',
                      )}
                    >
                      Book Title
                    </Link>
                    <p className='mt-1 text-sm text-neutral-600 dark:text-neutral-200'>book date</p>
                  </div>
                </div>
                <button
                  className={twMerge(
                    'absolute -left-1 -top-1 rounded px-1.5 py-0.5 text-xs font-medium',
                    'bg-red-500 text-white transition-all hover:bg-red-600',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400',
                  )}
                >
                  X
                </button>
              </div>

              <div className='flex items-center gap-3'>
                <Link
                  href='#'
                  className='rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500'
                >
                  {true ? (
                    <div className='relative h-16 w-16'>
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        fill
                        className={twMerge('rounded-full object-cover brightness-90 hover:brightness-100')}
                        unoptimized
                      />
                    </div>
                  ) : (
                    <div className='flex h-16 w-16 items-center justify-center rounded-full bg-neutral-200 dark:bg-neutral-800'>
                      <Image
                        alt={'lala'}
                        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                        unoptimized
                        className='h-8 w-8 text-neutral-500'
                      />
                    </div>
                  )}
                </Link>
                <div>
                  <Link
                    href='#'
                    className={twMerge(
                      'rounded text-[15px] font-medium text-neutral-700 transition-all duration-200 dark:text-neutral-100',
                      'hover:text-sky-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500',
                    )}
                  >
                    Author Name
                  </Link>
                  {true ? (
                    <a
                      href='#'
                      className={twMerge(
                        'mt-1 flex w-16 items-center rounded text-sm font-medium transition-all duration-200',
                        'text-sky-500 hover:text-sky-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500',
                      )}
                      target='_blank'
                      rel='noreferrer'
                    >
                      Web
                      <ArrowRightIcon className='ml-1 h-4 w-4' />
                    </a>
                  ) : (
                    <p>-</p>
                  )}
                </div>
              </div>

              <div className='relative'>
                <div className='flex items-center gap-3'>
                  <Link
                    href='#'
                    className='rounded-full focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500'
                  >
                    {true ? (
                      <div className='relative h-16 w-16'>
                        <Image
                          alt={'lala'}
                          src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                          fill
                          className={twMerge('rounded-full object-cover brightness-90 hover:brightness-100')}
                          unoptimized
                        />
                      </div>
                    ) : (
                      <div className='flex h-16 w-16 items-center justify-center rounded-full bg-neutral-200 dark:bg-neutral-800'>
                        <Image
                          alt={'lala'}
                          src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                          unoptimized
                          className='h-8 w-8 text-neutral-500'
                        />
                      </div>
                    )}
                  </Link>
                  <div>
                    <Link
                      href='#'
                      className={twMerge(
                        'rounded text-[15px] font-medium text-neutral-700 transition-all duration-200 dark:text-neutral-100',
                        'hover:text-sky-500 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500 dark:hover:text-sky-500',
                      )}
                    >
                      Author Name
                    </Link>
                    {true ? (
                      <a
                        href='#'
                        className={twMerge(
                          'mt-1 flex w-16 items-center rounded text-sm font-medium transition-all duration-200',
                          'text-sky-500 hover:text-sky-600 focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-sky-500',
                        )}
                        target='_blank'
                        rel='noreferrer'
                      >
                        Web
                        <ArrowRightIcon className='ml-1 h-4 w-4' />
                      </a>
                    ) : (
                      <p>-</p>
                    )}
                  </div>
                </div>
                <button
                  className={twMerge(
                    'absolute -left-1 -top-1 rounded-full px-1.5 py-0.5 text-xs font-medium',
                    'bg-red-500 text-white transition-all hover:bg-red-600',
                    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-red-400',
                  )}
                >
                  X
                </button>
              </div>
            </div>
          </Section>

          <div className='fixed bottom-20 right-3 z-10 mx-4 rounded bg-gray-100 bg-opacity-20 !py-2 px-2 backdrop-blur backdrop-filter dark:bg-neutral-800 dark:bg-opacity-40 md:right-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-neutral-800 p-1 text-white transition-all duration-300 ease-in hover:bg-neutral-700'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-gray-100 p-1 transition-all duration-300 ease-in hover:bg-gray-200'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>

        <Footer />
      </Layout>
    </div>
  );
}
