import { useContext, useEffect, useRef } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import Link from 'next/link';
import BackToTop from '@components/BackToTop';
import Dotgrid from '@components/hover/Dotgrid';
import Pointer from '@components/hover/Pointer';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import Section from '@components/Section';
import { MoonIcon, SunIcon } from '@heroicons/react/outline';
import { GlobalContext } from '@utils/GlobalContext';

function Div() {
  const divRef = useRef(null);
  const mainRef = useRef(null);
  function mouseMoveEvent(e) {
    const { x, y } = mainRef.current.getBoundingClientRect();
    mainRef.current.style.setProperty('--xx', e.clientX - x);
    mainRef.current.style.setProperty('--yy', e.clientY - y);
  }

  useEffect(() => {
    if (divRef) {
      divRef.current.addEventListener('mousemove', mouseMoveEvent);
    }
    return () => divRef.current?.removeEventListener('mousemove', mouseMoveEvent);
  }, [divRef]);

  return (
    <div ref={mainRef} className='dark:bg-neutral-800 w-full border dark:border-neutral-700 rounded-lg'>
      <div
        ref={divRef}
        className='shiny relative overflow-hidden cursor-pointer h-60 flex justify-center items-center text-center'
      >
        <div>
          <h1 className='dark:text-white font-medium text-2xl'>Text 1</h1>
          <h2 className='dark:text-white text-lg'>Text 1</h2>
        </div>
      </div>
    </div>
  );
}

export default function Hover() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);
  const cardRef = useRef(null);
  let X,
    Y = 0;

  function mouseMoveEvent(e) {
    let w = cardRef.current?.clientWidth;
    let h = cardRef.current?.clientHeight;
    let b = cardRef.current?.getBoundingClientRect();
    // console.log("mousemove")
    // console.log("W : ", w)
    // console.log("H : ", h)
    // console.log("B : ", b)
    X = (e.clientX - b?.left) / w;
    Y = (e.clientY - b?.top) / h;
    // console.log("X : ", X);
    // console.log("Y : ", Y);
    let rX = -(X - 0.5) * 10;
    let rY = (Y - 0.5) * 10;
    let bgX = 40 + 20 * X;
    let bgY = 40 + 20 * Y;
    document.documentElement.style.setProperty('--x', 100 * X + '%');
    document.documentElement.style.setProperty('--y', 100 * Y + '%');
    document.documentElement.style.setProperty('--bg-x', bgX + '%');
    document.documentElement.style.setProperty('--bg-y', bgY + '%');
    document.documentElement.style.setProperty('--r-x', rX + 'deg');
    document.documentElement.style.setProperty('--r-y', rY + 'deg');
  }

  function mouseLeaveEvent(e) {
    console.log('mouseleave');
    document.documentElement.style.removeProperty('--x');
    document.documentElement.style.removeProperty('--y');
    document.documentElement.style.removeProperty('--bg-x');
    document.documentElement.style.removeProperty('--bg-y');
    document.documentElement.style.removeProperty('--r-x');
    document.documentElement.style.removeProperty('--r-y');
  }

  useEffect(() => {
    if (cardRef) {
      cardRef.current.addEventListener('mousemove', mouseMoveEvent);
      cardRef.current.addEventListener('mouseleave', mouseLeaveEvent);
    }
    return () => {
      cardRef.current?.removeEventListener('mousemove', mouseMoveEvent);
      cardRef.current?.removeEventListener('mouseleave', mouseLeaveEvent);
    };
  }, [cardRef]);

  return (
    <>
      <Head>
        <title>Hover Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='max-w-7xl mx-auto px-4 sm:px-6 md:px-8 py-8'>
          <div className='pointer-events-none absolute inset-0'>
            <div className='min-h-full w-full max-w-7xl grid-cols-3 gap-3.5 grid px-4 sm:px-6 md:px-8 mx-auto'>
              <div className='border-x border-neutral-200/80 dark:border-white/5'></div>
              <div className='border-x border-neutral-200/80 dark:border-white/5'></div>
              <div className='border-x border-neutral-200/80 dark:border-white/5'></div>
            </div>
          </div>

          <Pointer />

          <Dotgrid />

          <Link href='https://linear.app/customers' className='block text-sky-500'>
            https://linear.app/customers
          </Link>
          <Link href='https://codepen.io/akella/pen/XWYrRmb' className='block text-sky-500'>
            https://codepen.io/akella/pen/XWYrRmb
          </Link>

          <div ref={cardRef} className='card my-8'>
            <div className='card__wrapper'>
              <div className='card__3d'>
                <div className='card__image'>
                  <img src='http://allyourhtml.club/carousel/image.webp' alt='' />
                </div>
                <div className='card__layer1'></div>
                <div className='card__layer2'></div>
              </div>
            </div>
          </div>

          <div className='flex overflow-x-auto gap-4 pb-4 relative z-10'>
            <Div />
            <Div />
            <Div />
          </div>

          <Section id='link-hover-underline' name='Link Hover Underline'>
            <ul className='space-y-4 my-8'>
              <li>
                <Link href='/' className='dark:text-white underlined inline-block'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/' className='dark:text-white hover-underline-animation inline-block'>
                  Home
                </Link>
              </li>
              <li>
                <Link href='/' className='dark:text-white underline-center-animation'>
                  Home
                </Link>
              </li>
            </ul>
          </Section>

          <Section id='card-hover-translate' name='Card Hover Translate'>
            <div className='grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4'>
              <a href='#!' className='relative h-72 rounded-md group overflow-hidden border dark:border-neutral-700'>
                <div className='ease-in-out transition-transform duration-500 transform group-hover:-translate-y-24'>
                  <div className='h-40 relative'>
                    <Image
                      className='w-full object-center rounded-t-md'
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      alt='hero'
                      layout='fill'
                    />
                  </div>
                  <div className='p-4'>
                    <h5 className='font-semibold text-lg line-clamp-2 mb-2'>
                      Hover Image Translate Aliqua anim quis enim et
                    </h5>
                    <p className='line-clamp-4'>
                      Aliqua anim quis enim et. Do nulla cupidatat sunt qui elit esse officia incididunt ut. Nulla
                      deserunt et aliquip cupidatat nulla ex irure ullamco nulla fugiat officia. Sit duis exercitation
                      elit mollit.
                    </p>
                  </div>
                </div>
                <div className='absolute bottom-0 inset-x-0 px-4 py-1 translate-y-8 bg-white dark:bg-neutral-900 border-t  dark:border-t-neutral-700 ease-in-out transition-transform duration-[600ms] transform group-hover:translate-y-0'>
                  <p>Bottom</p>
                </div>
              </a>
              <a href='#!' className='relative h-72 rounded-md group overflow-hidden border dark:border-neutral-700'>
                <div className='ease-in-out transition-transform duration-500 transform group-hover:-translate-y-28'>
                  <div className='h-40 relative'>
                    <Image
                      className='w-full object-center rounded-t-md'
                      src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                      alt='hero'
                      layout='fill'
                    />
                  </div>
                  <div className='p-4'>
                    <h5 className='font-semibold text-lg line-clamp-2 mb-2'>
                      Hover Image Translate Aliqua anim quis enim et
                    </h5>
                    <p className='line-clamp-4'>
                      Aliqua anim quis enim et. Do nulla cupidatat sunt qui elit esse officia incididunt ut. Nulla
                      deserunt et aliquip cupidatat nulla ex irure ullamco nulla fugiat officia. Sit duis exercitation
                      elit mollit.
                    </p>
                  </div>
                  <div className='px-4 py-2 border-t dark:border-t-neutral-700'>
                    <p>Bottom</p>
                  </div>
                </div>
              </a>
              <a href='#!' className='relative h-72 rounded-md group overflow-hidden border dark:border-neutral-700'>
                <div>
                  <Image
                    className='w-full object-center rounded-t-md'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='p-4 absolute inset-0 bg-black/50 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-500 ease-in-out'>
                    <div className='flex h-full items-end'>
                      <div>
                        <h5 className='font-semibold text-lg line-clamp-2 mb-2'>
                          Hover Image Translate Aliqua anim quis enim et
                        </h5>
                        <p className='line-clamp-4'>
                          Aliqua anim quis enim et. Do nulla cupidatat sunt qui elit esse officia incididunt ut. Nulla
                          deserunt et aliquip cupidatat nulla ex irure ullamco nulla fugiat officia. Sit duis
                          exercitation elit mollit.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              <a href='#!' className='relative h-72 rounded-md group overflow-hidden border dark:border-neutral-700'>
                <div>
                  <Image
                    className='w-full object-center rounded-t-md'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='p-4 absolute inset-0 bg-black/50 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out'>
                    <div className='flex h-full items-end translate-y-44 group-hover:translate-y-0 transition-transform ease-in-out duration-500'>
                      <div>
                        <h5 className='font-semibold text-lg line-clamp-2 mb-2'>
                          Hover Image Translate Aliqua anim quis enim et
                        </h5>
                        <p className='line-clamp-4'>
                          Aliqua anim quis enim et. Do nulla cupidatat sunt qui elit esse officia incididunt ut. Nulla
                          deserunt et aliquip cupidatat nulla ex irure ullamco nulla fugiat officia. Sit duis
                          exercitation elit mollit.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              <a href='#!' className='relative h-72 rounded-md group overflow-hidden border dark:border-neutral-700'>
                <div>
                  <Image
                    className='w-full object-center rounded-md'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='p-4 absolute inset-0 bg-black/50 text-white opacity-100 group-hover:opacity-0 transition-opacity duration-300 ease-in-out'>
                    <div className='flex h-full items-end'>
                      <h5 className='font-semibold text-lg text-center line-clamp-2 mb-2'>
                        Hover Image Translate Aliqua anim quis enim et
                      </h5>
                    </div>
                  </div>
                  <div className='p-4 absolute inset-0 bg-black/50 text-white opacity-0 group-hover:opacity-100 transition-opacity duration-300 ease-in-out'>
                    <div className='flex h-full items-end translate-y-44 group-hover:translate-y-0 transition-transform ease-in-out duration-500'>
                      <div>
                        <h5 className='font-semibold text-lg line-clamp-2 mb-2'>
                          Hover Image Translate Aliqua anim quis enim et
                        </h5>
                        <p className='line-clamp-4'>
                          Aliqua anim quis enim et. Do nulla cupidatat sunt qui elit esse officia incididunt ut. Nulla
                          deserunt et aliquip cupidatat nulla ex irure ullamco nulla fugiat officia. Sit duis
                          exercitation elit mollit.
                        </p>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
              <a href='#!' className='group relative'>
                <div className='bg-neutral-200 dark:bg-neutral-950 h-full absolute inset-0 rounded-md'></div>
                <div className='relative h-full group-hover:translate-x-4 group-hover:-translate-y-3 transition-transform duration-500 shadow-2xl'>
                  <Image
                    className='w-full object-center rounded-md brightness-90 group-hover:brightness-100 transition-all duration-300'
                    src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
                    alt='hero'
                    layout='fill'
                  />
                  <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
                    <div className='flex justify-center items-end h-full'>
                      <div className='text-white m-6'>
                        <h5 className='font-semibold text-lg text-center line-clamp-2'>
                          Hover Image Brightness Translate
                        </h5>
                      </div>
                    </div>
                  </div>
                </div>
              </a>
            </div>
          </Section>

          <Section id='hover-mask-image' name='Hover Mask Image'>
            <Logo />
            <div className=' my-8 grid grid-cols-1 gap-8 sm:grid-cols-2 lg:grid-cols-4'>
              <Card />
            </div>
          </Section>

          <div className='!py-2 px-2 rounded mx-4 bg-opacity-20 dark:bg-opacity-40 bg-gray-100 dark:bg-neutral-800 backdrop-filter backdrop-blur fixed bottom-20 right-3 md:right-10 z-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='w-8 h-8 p-1 transition-all ease-in duration-300 bg-neutral-800 hover:bg-neutral-700 text-white rounded-full'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='w-8 h-8 p-1 transition-all ease-in duration-300 bg-gray-100 hover:bg-gray-200 rounded-full'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>
      </Layout>
    </>
  );
}

function Card() {
  return (
    <a href='#!' className='relative h-64 rounded-md group overflow-hidden'>
      <Image
        className='w-full object-center rounded-md'
        src='https://images.unsplash.com/photo-1653043704077-5652028726f4?w=387&q=80'
        alt='hero'
        layout='fill'
      />
      <div className='absolute inset-0 rounded-md bg-gradient-to-b from-transparent via-transparent to-neutral-950'>
        <div className='flex justify-center items-end h-full'>
          <div className='text-white m-6'>
            <h5 className='font-semibold text-lg text-center line-clamp-2'>Hover Image Brightness</h5>
          </div>
        </div>
      </div>
      <style jsx>{`
        a {
          mask-image: linear-gradient(60deg, black 25%, rgba(0, 0, 0, 0.1) 50%, black 75%);
          mask-size: 450%;
          mask-position: 0%;
        }
        a:hover {
          mask-position: 100%;
          transition:
            mask-position 1.5s ease,
            -webkit-mask-position 1.5s ease;
        }
      `}</style>
    </a>
  );
}

function Logo() {
  return (
    <svg height='40' viewBox='0 0 361 70' fill='none' xmlns='http://www.w3.org/2000/svg' className='hover:opacity-75'>
      <path
        d='M114.913 33.2763v28.7642h-11.57V12.9496h11.059v8.3416h.575c1.129-2.7485 2.93-4.9325 5.401-6.5518 2.493-1.6193 5.572-2.429 9.237-2.429 3.388 0 6.339.7244 8.853 2.1733 2.535 1.4489 4.496 3.5476 5.88 6.2962 1.407 2.7486 2.099 6.0831 2.078 10.0035v31.2571h-11.57V32.5732c0-3.2813-.852-5.8487-2.557-7.7024-1.683-1.8537-4.016-2.7806-6.999-2.7806-2.024 0-3.824.4475-5.401 1.3424-1.556.8736-2.781 2.1413-3.676 3.8032-.873 1.662-1.31 3.6755-1.31 6.0405Zm61.407 29.723c-4.922 0-9.172-1.0227-12.752-3.0681-3.558-2.0668-6.296-4.9858-8.214-8.7572-1.917-3.7926-2.876-8.2563-2.876-13.3913 0-5.0497.959-9.4815 2.876-13.2954 1.939-3.8353 4.645-6.8182 8.118-8.9489 3.473-2.152 7.553-3.228 12.241-3.228 3.026 0 5.881.4901 8.565 1.4702 2.706.9588 5.093 2.4503 7.159 4.4744 2.088 2.0242 3.729 4.6023 4.922 7.7344 1.193 3.1108 1.79 6.8182 1.79 11.1221v3.5476h-40.238v-7.7983h29.148c-.021-2.2159-.501-4.1868-1.438-5.9126-.938-1.7472-2.248-3.1215-3.931-4.1229-1.662-1.0014-3.601-1.5021-5.817-1.5021-2.365 0-4.443.5753-6.232 1.7258-1.79 1.1293-3.186 2.6208-4.187 4.4745-.98 1.8324-1.481 3.8459-1.502 6.0405v6.8075c0 2.8551.522 5.3054 1.566 7.3508 1.044 2.0242 2.503 3.5796 4.378 4.6662 1.875 1.0654 4.07 1.598 6.584 1.598 1.683 0 3.207-.2343 4.57-.7031 1.364-.49 2.546-1.2038 3.548-2.1413 1.001-.9375 1.758-2.0987 2.269-3.4837l10.803 1.2145c-.682 2.8551-1.982 5.348-3.9 7.4787-1.896 2.1094-4.325 3.75-7.286 4.9219-2.962 1.1506-6.35 1.7258-10.164 1.7258Zm34.777-50.0497 9.908 18.1215 10.067-18.1215h12.241l-14.798 24.5455 15.054 24.5454h-12.177l-10.387-17.674-10.291 17.674h-12.273l14.957-24.5454-14.574-24.5455h12.273Zm63.878 0v8.9489h-28.221v-8.9489h28.221ZM253.722 1.18825h11.569V47.2749c0 1.5554.235 2.7486.704 3.5795.49.8097 1.129 1.3637 1.917 1.662s1.662.4474 2.621.4474c.724 0 1.385-.0532 1.981-.1598.618-.1065 1.087-.2024 1.407-.2876l1.949 9.0447c-.618.2131-1.502.4475-2.652.7031-1.13.2557-2.515.4049-4.155.4475-2.898.0852-5.508-.3516-7.831-1.3104-2.322-.9801-4.165-2.4929-5.529-4.5383-1.342-2.0455-2.003-4.6023-1.981-7.6705V1.18825Zm29.129 60.85225V12.9496h11.218v8.1818h.512c.895-2.8338 2.429-5.0177 4.602-6.5518 2.173-1.5554 4.677-2.3331 7.511-2.3331 1.321 0 2.535.1598 3.643.4794 1.108.3196 2.088.7564 2.94 1.3104l-3.579 9.588c-.618-.2983-1.3-.5433-2.046-.7351-.745-.1917-1.587-.2876-2.524-.2876-2.003 0-3.814.4474-5.434 1.3423-1.619.8949-2.908 2.1414-3.867 3.7394-.937 1.5767-1.406 3.4091-1.406 5.4971v28.8601h-11.57Zm51.222.863c-3.856 0-7.308-.9908-10.355-2.9723-3.047-1.9816-5.454-4.858-7.223-8.6293-1.768-3.7713-2.652-8.3523-2.652-13.7429 0-5.4546.894-10.0568 2.684-13.8068 1.811-3.7713 4.251-6.6158 7.319-8.5334 3.068-1.9389 6.488-2.9084 10.259-2.9084 2.877 0 5.242.4901 7.095 1.4702 1.854.9588 3.324 2.12 4.411 3.4836 1.087 1.3424 1.928 2.6101 2.525 3.8033h.479v-8.1179h11.602v49.0909h-11.378v-7.7343h-.703c-.597 1.1931-1.46 2.4609-2.589 3.8032-1.129 1.321-2.621 2.4503-4.474 3.3878-1.854.9375-4.187 1.4063-7 1.4063Zm3.228-9.4922c2.451 0 4.539-.6605 6.265-1.9816 1.725-1.3423 3.036-3.2066 3.931-5.593s1.342-5.1669 1.342-8.3416c0-3.1747-.447-5.934-1.342-8.2777-.874-2.3438-2.174-4.1655-3.9-5.4652-1.704-1.2997-3.803-1.9496-6.296-1.9496-2.578 0-4.73.6712-6.456 2.0135s-3.025 3.196-3.899 5.5611c-.873 2.365-1.31 5.071-1.31 8.1179 0 3.0682.437 5.8061 1.31 8.2138.895 2.3863 2.205 4.272 3.931 5.6569 1.747 1.3636 3.889 2.0455 6.424 2.0455Z'
        fill='currentColor'
      />
      <path
        d='m64.8833 1.81335-2.8464 2.84638C47.1274 19.5692 22.9543 19.5692 8.04485 4.65972L5.19848 1.81335c-.93479-.93478-2.45037-.93478-3.38515 0-.93479.93478-.93478 2.45037 0 3.38515L4.6597 8.04487c14.9095 14.90953 14.9095 39.08263 0 53.99213l-2.84637 2.8463c-.93479.9348-.93479 2.4504 0 3.3852.93478.9348 2.45037.9348 3.38515 0l2.84637-2.8464c14.90955-14.9095 39.08255-14.9095 53.99205 0l2.8464 2.8464c.9348.9348 2.4504.9348 3.3852 0 .9347-.9348.9347-2.4504 0-3.3852l-2.8464-2.8463c-14.9095-14.9095-14.9095-39.0826 0-53.99213l2.8464-2.84637c.9347-.93478.9347-2.45037 0-3.38515-.9348-.93478-2.4504-.93478-3.3852 0Z'
        fill='currentColor'
        stroke='currentColor'
        strokeWidth='2'
      />
      <style jsx>{`
        svg {
          mask-image: linear-gradient(60deg, black 25%, rgba(0, 0, 0, 0.2) 50%, black 75%);
          mask-size: 400%;
          mask-position: 0%;
        }
        svg:hover {
          mask-position: 100%;
          transition:
            mask-position 1.5s ease,
            -webkit-mask-position 1.5s ease;
        }
      `}</style>
    </svg>
  );
}
