import Head from 'next/head';
import Image from 'next/image';

import Footer from '@components/Footer';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';

export default function Home() {
  return (
    <div>
      <Head>
        <title>Home Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 sm:px-6 md:px-8'>
          <section className='body-font text-gray-600'>
            <div className='mx-auto flex flex-col items-center py-24 md:flex-row'>
              <div className='mb-16 flex flex-col items-center text-center md:mb-0 md:w-1/2 md:items-start md:pr-16 md:text-left lg:flex-grow lg:pr-24'>
                <h1 className='title-font mb-4 text-3xl font-medium text-gray-900 dark:text-neutral-200 sm:text-4xl'>
                  Before they sold out
                </h1>
                <p className='mb-8 leading-relaxed dark:text-neutral-300'>
                  Copper mug try-hard pitchfork pour-over freegan heirloom neutra air plant cold-pressed tacos poke
                  beard tote bag. Heirloom echo park mlkshk tote bag selvage hot chicken authentic tumeric truffaut
                  hexagon try-hard chambray.
                </p>
                <div className='flex justify-center'>
                  <button className='inline-flex rounded border-0 bg-gray-800 px-6 py-2 text-lg text-white hover:bg-gray-900 focus:outline-none'>
                    Button
                  </button>
                  <button className='ml-4 inline-flex rounded border-0 bg-gray-100 px-6 py-2 text-lg text-gray-700 hover:bg-gray-200 focus:outline-none'>
                    Button
                  </button>
                </div>
              </div>
              <div className='w-5/6 md:w-1/2 lg:w-full lg:max-w-lg'>
                <Image
                  className='rounded object-cover object-center'
                  src='https://dummyimage.com/720x600'
                  alt='hero'
                  width={500}
                  height={500}
                />
              </div>
            </div>
          </section>
        </main>

        <Footer />
      </Layout>
    </div>
  );
}
