import { useContext } from 'react';
import Head from 'next/head';
import Link from 'next/link';
import { MoonIcon, SunIcon } from '@heroicons/react/outline';
import { GlobalContext } from '@utils/GlobalContext';

import logger from '@/utils/logger';

import BackToTop from '@components/BackToTop';
import Footer from '@components/Footer';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import Section from '@components/Section';
import TocLink from '@components/TocLink';

export default function Logger() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);

  logger.info('a INFO message from Logger Page');
  logger.info(
    {
      info: 'Info',
    },
    'a INFO message from Logger Page',
  );

  logger.warn('a WARN message from Logger Page');
  logger.warn(
    {
      warn: 'Warn',
    },
    'a WARN message from Logger Page',
  );

  logger.error('a ERROR message from Logger Page');
  logger.error(
    {
      error: 'Error',
    },
    'a ERROR message from Logger Page',
  );

  return (
    <div>
      <Head>
        <title>Logger Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 pb-16 sm:px-6 md:px-8'>
          <Section id='components' name='Logger TOC'>
            <div className='grid sm:grid-cols-2 md:grid-cols-3'>
              <div>{/* <TocLink href='#input-file' text='Input File' /> */}</div>
            </div>
          </Section>

          <div className='min-h-screen'>
            <p>ENV = {process.env.NODE_ENV}</p>
            <p>
              <Link href='/logger' className='text-sky-500'>
                <b>/logger</b>
              </Link>{' '}
              page show log to <b>browser console</b>
            </p>
            <p>
              <b>logger.debug()</b> not work in <b>browser console</b>
            </p>
            <p>
              <Link href='/api/logger' className='text-sky-500'>
                <b>/api/logger</b>
              </Link>{' '}
              API endpoint show log to <b>server console</b>
            </p>
            <p>
              this logger also create log file <b>logger.log</b> and <b>logger-pretty.log</b>
            </p>
          </div>

          <div className='fixed bottom-20 right-3 z-10 mx-4 rounded bg-gray-100 bg-opacity-20 !py-2 px-2 backdrop-blur backdrop-filter dark:bg-neutral-800 dark:bg-opacity-40 md:right-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-neutral-800 p-1 text-white transition-all duration-300 ease-in hover:bg-neutral-700'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-gray-100 p-1 transition-all duration-300 ease-in hover:bg-gray-200'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>

        <Footer />
      </Layout>
    </div>
  );
}
