import { useContext } from 'react';
import Head from 'next/head';
import BackToTop from '@components/BackToTop';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import { MoonIcon, SunIcon } from '@heroicons/react/outline';
import { Splide, SplideSlide, SplideTrack } from '@splidejs/react-splide';
import { AutoScroll } from '@splidejs/splide-extension-auto-scroll';
import { GlobalContext } from '@utils/GlobalContext';

// Default theme
import '@splidejs/react-splide/css';

// or other themes
// import '@splidejs/react-splide/css/skyblue';
// import '@splidejs/react-splide/css/sea-green';
// or only core styles
// import '@splidejs/react-splide/css/core';

export default function Slider() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);
  return (
    <>
      <Head>
        <title>Splide.js Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 py-8 sm:px-6 md:px-8'>
          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Splide Nav Pagination
          </h1>
          <Splide
            aria-label='My Favorite Images'
            options={{
              type: 'loop',
              autoplay: true,
              rewind: true,
              gap: '1rem',
              drag: true,
            }}
          >
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SplideSlide>
          </Splide>

          <h1 className='title-font mb-2 mt-6 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Splide Auto Scroll
          </h1>
          <Splide
            aria-label='My Favorite Images'
            options={{
              type: 'loop',
              drag: false,
              focus: 'center',
              gap: '1rem',
              pagination: false,
              arrows: false,
              perPage: 3,
              autoScroll: {
                speed: 2,
                pauseOnHover: false,
              },
            }}
            extensions={{ AutoScroll }}
          >
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SplideSlide>
            <SplideSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SplideSlide>
          </Splide>

          <h1 className='title-font mb-2 mt-6 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Splide Custom Nav
          </h1>
          <Splide
            aria-label='My Favorite Images'
            options={{
              type: 'loop',
              autoplay: true,
              perPage: 3,
              rewind: true,
              gap: '1rem',
            }}
            hasTrack={false}
          >
            <div>
              <SplideTrack>
                <SplideSlide>
                  <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                    <div>
                      <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                      <h2 className='text-lg text-white'>Text 1</h2>
                    </div>
                  </div>
                </SplideSlide>
                <SplideSlide>
                  <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                    <div>
                      <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                      <h2 className='text-lg text-white'>Text 2</h2>
                    </div>
                  </div>
                </SplideSlide>
                <SplideSlide>
                  <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                    <div>
                      <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                      <h2 className='text-lg text-white'>Text 3</h2>
                    </div>
                  </div>
                </SplideSlide>
                <SplideSlide>
                  <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                    <div>
                      <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                      <h2 className='text-lg text-white'>Text 4</h2>
                    </div>
                  </div>
                </SplideSlide>
              </SplideTrack>
              <div className='splide__arrows'>
                <button className='splide__arrow splide__arrow--prev'>Prev</button>
                <button className='splide__arrow splide__arrow--next'>Next</button>
              </div>
              <div className='splide__progress'>
                <div className='splide__progress__bar' />
              </div>

              <button className='splide__toggle' type='button'>
                <span className='splide__toggle__play'>Play</span>
                <span className='splide__toggle__pause'>Pause</span>
              </button>
            </div>
          </Splide>

          <div className='fixed bottom-20 right-3 z-10 mx-4 rounded bg-gray-100 bg-opacity-20 !py-2 px-2 backdrop-blur backdrop-filter dark:bg-neutral-800 dark:bg-opacity-40 md:right-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-neutral-800 p-1 text-white transition-all duration-300 ease-in hover:bg-neutral-700'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-gray-100 p-1 transition-all duration-300 ease-in hover:bg-gray-200'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>
      </Layout>
    </>
  );
}
