import { useContext } from 'react';
import Head from 'next/head';
import BackToTop from '@components/BackToTop';
import Layout from '@components/Layout';
import Navbar from '@components/Navbar';
import { MoonIcon, SunIcon } from '@heroicons/react/outline';
import { GlobalContext } from '@utils/GlobalContext';
// import SwiperCore, { Autoplay } from 'swiper';
import SwiperCore, { A11y, Autoplay, Navigation, Pagination, Scrollbar } from 'swiper';
// Import Swiper React components
import { Swiper, SwiperSlide } from 'swiper/react';

import 'swiper/css';
import 'swiper/css/navigation';
import 'swiper/css/pagination';
import 'swiper/css/autoplay';
import 'swiper/css/scrollbar';

export default function Slider() {
  const { darkMode, setDarkMode } = useContext(GlobalContext);
  return (
    <>
      <Head>
        <title>Swiper.js Page</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <Navbar />

      <Layout>
        <main className='mx-auto max-w-7xl px-4 py-8 sm:px-6 md:px-8'>
          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Nav Pagination Scrollbar
          </h1>
          <Swiper
            className='mb-5'
            modules={[Autoplay, Navigation, Pagination, Scrollbar, A11y]}
            spaceBetween={20}
            slidesPerView={3}
            autoplay={true}
            navigation={true}
            pagination={{ clickable: true }}
            scrollbar={{ draggable: true }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Pagination Custom Dot
          </h1>
          <Swiper
            className='swiper-custom-pagination-dot mb-5'
            modules={[Autoplay, Pagination, A11y]}
            spaceBetween={20}
            slidesPerView={3}
            // autoplay={true}
            pagination={{ clickable: true }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Pagination Custom Progress
          </h1>
          <Swiper
            className='swiper-custom-pagination-scroll mb-5'
            modules={[Autoplay, Scrollbar, A11y]}
            spaceBetween={20}
            slidesPerView={3}
            autoplay={true}
            scrollbar={{ draggable: true }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Responsive
          </h1>
          <Swiper
            className='mb-5'
            modules={[Autoplay, Navigation, A11y]}
            spaceBetween={20}
            slidesPerView={3}
            autoplay={true}
            navigation={true}
            loop={true}
            breakpoints={{
              320: {
                slidesPerView: 1,
                spaceBetween: 24,
              },
              640: {
                slidesPerView: 2,
                spaceBetween: 24,
              },
              768: {
                slidesPerView: 2,
                spaceBetween: 24,
              },
              1024: {
                slidesPerView: 3,
                spaceBetween: 24,
              },
            }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-600 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Nav Loop
          </h1>
          <Swiper
            className='mb-5'
            modules={[Autoplay, Navigation, A11y]}
            spaceBetween={20}
            slidesPerView={2}
            autoplay={true}
            navigation={true}
            loop={true}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Nav Progress
          </h1>
          <Swiper
            className='mb-5'
            modules={[Autoplay, Pagination, Navigation, A11y]}
            spaceBetween={20}
            slidesPerView={3}
            autoplay={true}
            navigation={true}
            pagination={{
              type: 'progressbar',
            }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-400 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-400 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-400 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-400 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Nav Custom Button
          </h1>
          <Swiper
            className='swiper-custom-nav mb-5'
            modules={[Autoplay, Navigation, A11y]}
            spaceBetween={20}
            slidesPerView={2}
            autoplay={true}
            navigation={true}
            loop={true}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font mb-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper Item Centered
          </h1>
          <Swiper
            className='swiper-custom-nav mb-5'
            modules={[Autoplay, Navigation, A11y]}
            spaceBetween={24}
            slidesPerView={3}
            centeredSlides={true}
            autoplay={true}
            navigation={true}
            loop={true}
            breakpoints={{
              320: {
                slidesPerView: 1,
                spaceBetween: 24,
              },
              640: {
                slidesPerView: 2,
                spaceBetween: 24,
              },
              768: {
                slidesPerView: 2,
                spaceBetween: 24,
              },
              1024: {
                slidesPerView: 2,
                spaceBetween: 24,
              },
            }}
          >
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide>
              <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font my-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper shows a bit previous/next slides
          </h1>
          <Swiper
            className='swiper-custom-nav mb-5'
            modules={[Navigation, A11y]}
            spaceBetween={16}
            // this shows a bit of the previous/next slides
            slidesPerView={1.2}
            navigation={true}
            breakpoints={{
              320: {
                slidesPerView: 1.2,
                spaceBetween: 16,
              },
              640: {
                slidesPerView: 2.5,
                spaceBetween: 16,
              },
            }}
          >
            <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
              <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                  <h2 className='text-lg text-white'>Text 1</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
              <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                  <h2 className='text-lg text-white'>Text 2</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
              <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                  <h2 className='text-lg text-white'>Text 3</h2>
                </div>
              </div>
            </SwiperSlide>
            <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
              <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                <div>
                  <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                  <h2 className='text-lg text-white'>Text 4</h2>
                </div>
              </div>
            </SwiperSlide>
          </Swiper>

          <h1 className='title-font my-2 text-2xl font-medium text-gray-900 dark:text-white sm:text-3xl'>
            Swiper continous play
          </h1>
          <Swiper
            className='swiper-continous-play mb-5'
            modules={[Autoplay, A11y]}
            spaceBetween={16}
            slidesPerView={3}
            loop={true}
            allowTouchMove={false}
            autoplay={{ delay: 0 }}
            speed={4000}
            breakpoints={{
              320: {
                slidesPerView: 1,
                spaceBetween: 16,
              },
              640: {
                slidesPerView: 3,
                spaceBetween: 16,
              },
            }}
          >
            <div className='swiper-wrapper'>
              <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
                <div className='flex h-60 items-center justify-center rounded-lg bg-purple-500 text-center'>
                  <div>
                    <h1 className='text-2xl font-medium text-white'>Text 1</h1>
                    <h2 className='text-lg text-white'>Text 1</h2>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
                <div className='flex h-60 items-center justify-center rounded-lg bg-emerald-500 text-center'>
                  <div>
                    <h1 className='text-2xl font-medium text-white'>Text 2</h1>
                    <h2 className='text-lg text-white'>Text 2</h2>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
                <div className='flex h-60 items-center justify-center rounded-lg bg-orange-500 text-center'>
                  <div>
                    <h1 className='text-2xl font-medium text-white'>Text 3</h1>
                    <h2 className='text-lg text-white'>Text 3</h2>
                  </div>
                </div>
              </SwiperSlide>
              <SwiperSlide className='shrink-0 sm:w-[350px] md:w-[400px] lg:w-[770px]'>
                <div className='flex h-60 items-center justify-center rounded-lg bg-red-500 text-center'>
                  <div>
                    <h1 className='text-2xl font-medium text-white'>Text 4</h1>
                    <h2 className='text-lg text-white'>Text 4</h2>
                  </div>
                </div>
              </SwiperSlide>
            </div>
          </Swiper>

          <div className='fixed bottom-20 right-3 z-10 mx-4 rounded bg-gray-100 bg-opacity-20 !py-2 px-2 backdrop-blur backdrop-filter dark:bg-neutral-800 dark:bg-opacity-40 md:right-10'>
            {darkMode ? (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-neutral-800 p-1 text-white transition-all duration-300 ease-in hover:bg-neutral-700'
              >
                <SunIcon />
              </button>
            ) : (
              <button
                onClick={() => setDarkMode(!darkMode)}
                aria-label='Change Theme'
                className='h-8 w-8 rounded-full bg-gray-100 p-1 transition-all duration-300 ease-in hover:bg-gray-200'
              >
                <MoonIcon />
              </button>
            )}
          </div>

          <BackToTop />
        </main>
      </Layout>
    </>
  );
}
